language: rust

rust:
  # - stable
  # - beta
  - nightly


# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/wasm-pack


addons:
  firefox: latest
  chrome : stable

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

script:

  - git clone https://github.com/najamelan/ws_stream
  - cd ws_stream
  - cargo build --example echo --release
  - cargo build --example echo_tt --release
  - cargo run --example echo --release &
  - cargo run --example echo_tt --release -- "127.0.0.1:3312"  &
  - cd ..
  - cargo test # for doc tests
  - wasm-pack test  --firefox --headless
  - wasm-pack test  --chrome  --headless
  - wasm-pack test  --firefox --headless --release
  - wasm-pack test  --chrome  --headless --release

